#!/usr/bin/env python3
"""Legacy generator for the pre-Komorebi flower icon.

The active launcher artwork is the generated raster image at
app/src/main/res/drawable-nodpi/komorebi_launcher_art.png. This script remains
only to make the former vector artwork reproducible from repository history.

The former app name referenced the zinnia (ヒャクニチソウ), so the icon is one: a dense double ring of
broad, notch-tipped ray petals around a disc ringed with tiny gold florets.

Everything is derived from the constants below rather than drawn by hand, so the petal count or
the palette can be changed in one place. Outputs:

  res/drawable/ic_launcher_background.xml   adaptive background (API 26+)
  res/drawable/ic_launcher_foreground.xml   adaptive foreground
  res/drawable/ic_launcher_monochrome.xml   themed-icon silhouette (API 33+)
  res/mipmap-anydpi-v26/ic_launcher*.xml    the adaptive icon itself
  res/mipmap-*/ic_launcher*.png             legacy raster fallback, needed because minSdk is 24

The PNGs are rendered from the same geometry through inkscape, then cropped to the 72/108 window a
launcher would show and masked, so they match what API 26+ devices draw.
"""

import math
import pathlib
import shutil
import subprocess
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
RES = ROOT / "app/src/main/res"

# Adaptive icons are 108x108dp with only the central 66dp guaranteed visible after masking.
SIZE = 108.0
CX = CY = SIZE / 2

# --- the flower -----------------------------------------------------------------------------
# (petals, base radius, tip radius, half width, rotation offset in degrees)
BACK_RING = (13, 9.0, 32.5, 6.2, 0.0)
FRONT_RING = (11, 8.0, 24.0, 5.6, 15.0)

DISC_RADIUS = 8.4
FLORET_COUNT = 9
FLORET_ORBIT = 5.6
FLORET_RADIUS = 1.7

# Zinnia elegans in its common magenta, against a leaf green that keeps the bloom readable on both
# light and dark home screens.
BG_TOP = "#37795A"
BG_BOTTOM = "#123528"
BACK_PETAL = "#C62E63"
FRONT_PETAL = "#FA7C93"
DISC = "#7E4126"
FLORET = "#FFC64A"


def petal_path(base_r, tip_r, half_w, angle_deg):
    """One ray petal, pointing away from the centre at `angle_deg` (0 = straight up).

    Broad at the shoulder and notched at the apex, which is what makes a zinnia read as a zinnia
    rather than as a daisy. Built pointing up, then rotated, so the shape is described once.
    """
    length = tip_r - base_r
    notch = length * 0.10

    def y(fraction):
        return -(base_r + length * fraction)

    # Right side up to the apex, then mirrored back down the left side.
    points = [
        (half_w * 0.75, y(0.18), half_w, y(0.55), half_w * 0.72, y(0.86)),
        (half_w * 0.50, y(0.99), half_w * 0.22, -(tip_r - notch * 0.4), 0.0, -(tip_r - notch)),
        (-half_w * 0.22, -(tip_r - notch * 0.4), -half_w * 0.50, y(0.99), -half_w * 0.72, y(0.86)),
        (-half_w, y(0.55), -half_w * 0.75, y(0.18), 0.0, -base_r),
    ]

    rad = math.radians(angle_deg)
    sin, cos = math.sin(rad), math.cos(rad)

    def place(x, y_):
        return (CX + x * cos - y_ * sin, CY + x * sin + y_ * cos)

    start = place(0.0, -base_r)
    out = ["M%.2f,%.2f" % start]
    for curve in points:
        coords = []
        for i in range(0, 6, 2):
            coords.extend(place(curve[i], curve[i + 1]))
        out.append("C%.2f,%.2f %.2f,%.2f %.2f,%.2f" % tuple(coords))
    out.append("Z")
    return " ".join(out)


def ring_paths(ring):
    count, base_r, tip_r, half_w, offset = ring
    return [
        petal_path(base_r, tip_r, half_w, offset + 360.0 * i / count) for i in range(count)
    ]


def circle_path(cx, cy, r):
    """A circle as two arcs — vector drawables have no <circle>."""
    return (
        "M%.2f,%.2f a%.2f,%.2f 0 1,0 %.2f,0 a%.2f,%.2f 0 1,0 %.2f,0 Z"
        % (cx - r, cy, r, r, r * 2, r, r, -r * 2)
    )


def floret_paths():
    return [
        circle_path(
            CX + FLORET_ORBIT * math.cos(math.radians(-90 + 360.0 * i / FLORET_COUNT)),
            CY + FLORET_ORBIT * math.sin(math.radians(-90 + 360.0 * i / FLORET_COUNT)),
            FLORET_RADIUS,
        )
        for i in range(FLORET_COUNT)
    ]


def flower_layers():
    """(path, colour) in paint order, shared by the vector drawable and the SVG."""
    layers = [(p, BACK_PETAL) for p in ring_paths(BACK_RING)]
    layers += [(p, FRONT_PETAL) for p in ring_paths(FRONT_RING)]
    layers.append((circle_path(CX, CY, DISC_RADIUS), DISC))
    layers += [(p, FLORET) for p in floret_paths()]
    return layers


# --- vector drawables -----------------------------------------------------------------------

VECTOR_HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/gen_launcher_icon.py. Edit the script, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
"""


def vector(paths):
    body = "".join(
        '    <path\n        android:fillColor="%s"\n        android:pathData="%s" />\n'
        % (colour, path)
        for path, colour in paths
    )
    return VECTOR_HEADER + body + "</vector>\n"


def background_vector():
    # aapt:attr carries the gradient; a plain fillColor cannot express one.
    return """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/gen_launcher_icon.py. Edit the script, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:startX="0"
                android:startY="0"
                android:endX="108"
                android:endY="108"
                android:type="linear">
                <item android:offset="0" android:color="%s" />
                <item android:offset="1" android:color="%s" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
""" % (BG_TOP, BG_BOTTOM)


ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/gen_launcher_icon.py. Edit the script, not this file. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""


# --- legacy rasters -------------------------------------------------------------------------

# API 24 and 25 get no adaptive icon, so they need real bitmaps at every density.
DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}

# What a launcher actually shows out of the 108x108 canvas.
VISIBLE = 72.0


def svg(paths):
    body = "".join('  <path fill="%s" d="%s"/>\n' % (colour, path) for path, colour in paths)
    return """<svg xmlns="http://www.w3.org/2000/svg" width="108" height="108" viewBox="0 0 108 108">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="108" y2="108" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="%s"/>
      <stop offset="1" stop-color="%s"/>
    </linearGradient>
  </defs>
  <rect width="108" height="108" fill="url(#bg)"/>
%s</svg>
""" % (BG_TOP, BG_BOTTOM, body)


def render_legacy(paths):
    from PIL import Image, ImageDraw

    inkscape = shutil.which("inkscape")
    if inkscape is None:
        print("!! inkscape not found — skipping the legacy PNGs")
        return

    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        (tmp / "icon.svg").write_text(svg(paths))
        # Render generously oversized, then downsample per density for clean edges.
        master = tmp / "icon.png"
        subprocess.run(
            [inkscape, str(tmp / "icon.svg"), "--export-type=png",
             "--export-filename=" + str(master), "-w", "1080", "-h", "1080"],
            check=True, capture_output=True,
        )

        full = Image.open(master).convert("RGBA")
        # Crop to the window a launcher would show, so the bloom fills the legacy icon the same
        # way it does the adaptive one.
        inset = int(full.width * (SIZE - VISIBLE) / SIZE / 2)
        cropped = full.crop((inset, inset, full.width - inset, full.height - inset))

        for density, px in DENSITIES.items():
            out_dir = RES / ("mipmap-" + density)
            out_dir.mkdir(parents=True, exist_ok=True)
            scaled = cropped.resize((px, px), Image.LANCZOS)

            for name, mask in (("ic_launcher", "squircle"), ("ic_launcher_round", "circle")):
                supersample = 8
                layer = Image.new("L", (px * supersample, px * supersample), 0)
                draw = ImageDraw.Draw(layer)
                if mask == "circle":
                    draw.ellipse((0, 0, px * supersample - 1, px * supersample - 1), fill=255)
                else:
                    radius = int(px * supersample * 0.22)
                    draw.rounded_rectangle(
                        (0, 0, px * supersample - 1, px * supersample - 1),
                        radius=radius, fill=255,
                    )
                alpha = layer.resize((px, px), Image.LANCZOS)
                masked = scaled.copy()
                masked.putalpha(alpha)
                masked.save(out_dir / (name + ".png"))

        print("    legacy PNGs at %s" % ", ".join(DENSITIES))


def main():
    layers = flower_layers()

    drawable = RES / "drawable"
    drawable.mkdir(parents=True, exist_ok=True)
    (drawable / "ic_launcher_background.xml").write_text(background_vector())
    (drawable / "ic_launcher_foreground.xml").write_text(vector(layers))
    # The system tints the themed icon itself, so it is a flat silhouette in one colour.
    (drawable / "ic_launcher_monochrome.xml").write_text(
        vector([(path, "#FFFFFFFF") for path, _ in layers])
    )

    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    (anydpi / "ic_launcher.xml").write_text(ADAPTIVE)
    (anydpi / "ic_launcher_round.xml").write_text(ADAPTIVE)

    print("==> zinna-IME launcher icon")
    print("    %d + %d petals, %d florets" % (BACK_RING[0], FRONT_RING[0], FLORET_COUNT))
    render_legacy(layers)


if __name__ == "__main__":
    main()
